#! /usr/bin/env lua

HOME=os.getenv('HOME')
package.path = package.path .. ';lib/?.lua'
package.path = package.path .. ';lib/?/init.lua'
package.path = package.path .. ';' .. HOME .. '/.config/awesome/?.lua'
package.path = package.path .. ';' .. HOME .. '/.config/awesome/?/init.lua'
package.path = package.path .. ';/usr/local/share/awesome/lib/?.lua'
package.path = package.path .. ';/usr/local/share/awesome/lib/?/init.lua'
package.path = package.path .. ';/usr/share/awesome/lib/?.lua'
package.path = package.path .. ';/usr/share/awesome/lib/?/init.lua'

local lgi = require 'lgi'
local Gtk = lgi.require('Gtk')
local GLib = lgi.require('GLib')
local Gdk = lgi.require('Gdk')
local Gio = lgi.require('Gio')

local pluginManager = require('crappy.pluginManager')
local gui = require('crappy.gui')

-- The following is annoying:
GLib.set_prgname('awesome-config')
Gdk.set_program_class('Awesome-config')

local app = Gtk.Application.new('awesome-config.crappy.gui', Gio.ApplicationFlags.HANDLES_OPEN)

function app:on_startup()
   pluginManager.loadAllPlugins()
end

function app:on_shutdown()
end

function app:on_activate()
   local HOME = os.getenv('HOME')
   local fileName = HOME .. "/.config/awesome/crappy.json"
   local file = Gio.File.new_for_path(fileName)

   gui.newWindow(app, file)
end

function app:on_open(files)
   for i, file in ipairs(files) do
      log.message("Opening file " .. file:get_parse_name())
      gui.newWindow(app, file)
   end
end

app:run { arg[0], ... }
