#! /usr/bin/env lua

HOME=os.getenv('HOME')
package.path = package.path .. ';lib/?.lua'
package.path = package.path .. ';lib/?/init.lua'
package.path = package.path .. ';' .. HOME .. '/.config/awesome/?.lua'
package.path = package.path .. ';' .. HOME .. '/.config/awesome/?/init.lua'
package.path = package.path .. ';/usr/local/share/awesome/lib/?.lua'
package.path = package.path .. ';/usr/local/share/awesome/lib/?/init.lua'
package.path = package.path .. ';/usr/share/awesome/lib/?.lua'
package.path = package.path .. ';/usr/share/awesome/lib/?/init.lua'

local lgi = require 'lgi'
local Gtk = lgi.require('Gtk')
local GLib = lgi.require('GLib')
local Gdk = lgi.require('Gdk')

-- The following is annoying:
GLib.set_prgname('awesome-config')
Gdk.set_program_class('Awesome-config')

local gui = require('crappy.gui')

local app = Gtk.Application {application_id = 'awesome-config.crappy.gui'}
app.on_activate = gui.on_activate
app.on_startup = gui.on_startup
app.on_shutdown = gui.on_shutdown

app:run { arg[0], ... }
