#+TITLE: Awesome Configuration
#+OPTIONS: toc:4 H:4 p:t
This repository includes the following:
- awesome-config - A GUI for manipulating the 
- crappy - A library for reading configuration files for Awesome

* Crappy
Crappy reads a configuration file to configure Awesome 3.4.x or 3.5.x.  Specifically tested on 3.4.11 and 3.5.5.  The goal of this is to be able to move between multiple versions of Awesome and maintain the same basic configuration in a relatively easy to edit file.  JSON was chosen to allow for tools to be written in languages other than Lua to modify the configuration.
** Installation
Backup your configuration directory:
#+BEGIN_SRC sh
cp -a ~/.config/awesome ~/.config/awesome.bak-$(date +%F-%T)
#+END_SRC

Clone the repository anywhere you want:
#+BEGIN_SRC sh
git clone https://github.com/theasp/awesome-config.git
#+END_SRC

Make a symlink from your awesome config directory to the libraries:
#+BEGIN_SRC sh
ln -s $(pwd)/awesome-config/lib/* ~/.config/awesome/
#+END_SRC

Copy the example =rc.lua= and =crappy.json= to your config directory:
#+BEGIN_SRC sh
cp awesome-config/examples/{crappy.json,rc.lua} ~/.config/awesome/
#+END_SRC

Start awesome.
* Awesome Config
TODO
* Configuration File
Edit =~/.config/awesome/config.json=. as desired.  The configuration file is divided into =settings= and =startup=.  You can use your own functions in the configuration file by defining or requiring them =rc.lua= before starting crappy, or using anonymous functions.

Note that JSON does not allow comments.

** plugins
Plugins is a list of plugins (or psuedo-plugins using functions) and their configuration.

Each entry in the list is labelled with a plugin name which maps to information about the plugin, like whether it is enabled or it's settings.

See the contents of the =docs= directory for information about each plugin and it's settings.

Example:
#+BEGIN_SRC js
  "plugins": {
      "crappy.startup.theme": {
          "enabled": true,
          "settings": {
              "file": "/usr/share/awesome/themes/default/theme.lua",
              "font": "sans 10"
          }
      },
      ...
      "crappy.startup.menubar": {
          "enabled": true
      }
  }
#+END_SRC
** Extending
TODO
* Code Used
- crappy by Andrew Phillips <theasp@gmail.com> [[http://www.gnu.org/licenses/gpl-2.0.html][GPLv2]] includes code from:
  - ezconfig.lua by Georgi Valkov <georgi.t.valkov@gmail.com> [[http://www.gnu.org/licenses/gpl-2.0.html][GPLv2]]
    -  https://raw.githubusercontent.com/gvalkov/dotfiles-awesome/master/ezconfig.lua
  - JSON Encode/Decode in Pure LUA by Jeffrey Friedl  [[http://creativecommons.org/licenses/by/3.0/][CC-BY 3.0]]
    -  http://regex.info/blog/lua/json
  - rc.lua from Awesome by the awesome project [[http://www.gnu.org/licenses/gpl-2.0.html][GPLv2]]
    -  http://awesome.naquadah.org/

* Comments :noexport:
** TODO Document psuedo-plugins
** TODO Document awesome-config

# Local variables:
# org-ascii-charset: utf-8
# eval: (add-hook 'after-save-hook '(lambda () (org-ascii-export-to-ascii) (org-html-export-to-html) ) nil t)
# end:
