#+TITLE: Awesome Configuration
#+OPTIONS: toc:4 H:4 p:t
#+AUTHOR: Andrew Phillips
#+EMAIL: theasp@gmail.com

This repository includes the following:
- awesome-config - A GUI for manipulating the 
- crappy - A library for reading configuration files for Awesome

* Crappy
Crappy reads a configuration file to configure Awesome 3.4.x or 3.5.x.  Specifically tested on 3.4.11 and 3.5.5+.  The goal of this is to be able to move between multiple versions of Awesome and maintain the same basic configuration in a relatively easy to edit file.
** Installation from Git
Clone the repository anywhere you want:
#+BEGIN_SRC sh
git clone https://github.com/theasp/awesome-config.git
#+END_SRC

Backup your configuration directory:
#+BEGIN_SRC sh
cp -a ~/.config/awesome ~/.config/awesome.bak-$(date +%F-%T)
#+END_SRC

Make a symlink from your awesome config directory to the libraries:
#+BEGIN_SRC sh
ln -s $(pwd)/awesome-config/lib/* ~/.config/awesome/
#+END_SRC

Copy the example ~rc.lua~ and ~crappy-config.lua~ to your config directory:
#+BEGIN_SRC sh
cp awesome-config/examples/{crappy-config.lua,rc.lua} ~/.config/awesome/
#+END_SRC

Start awesome.
** Installation from APT on Ubuntu
For the released version:
#+BEGIN_SRC sh
sudo add-apt-repository ppa:theasp/awesome-config
#+END_SRC

For the latest snapshot version:
#+BEGIN_SRC sh
sudo add-apt-repository ppa:theasp/awesome-config-snapshot
#+END_SRC

Then run:
#+BEGIN_SRC sh
sudo apt-get update
sudo apt-get install awesome-config
#+END_SRC

Backup your configuration directory:
#+BEGIN_SRC sh
cp -a ~/.config/awesome ~/.config/awesome.bak-$(date +%F-%T)
#+END_SRC

Copy the example ~rc.lua~ and ~crappy-config.lua~ to your config directory:
#+BEGIN_SRC sh
cp /usr/share/doc/awesome-config/examples/{crappy-config.lua,rc.lua} ~/.config/awesome/
#+END_SRC

Start awesome.
* Configuration
You can use your own functions with crappy by defining or requiring them ~rc.lua~ before starting crappy, or using anonymous functions.
** Awesome Config GUI
Run ~awesome-config~ to start the configuration GUI.
** Manual Configuration
Edit ~.config/awesome/crappy-config.lua~ as desired.

A more detailed description of the configuration file is provided in the ~docs/config~ directory.
* Plugin API
See the plugin API documentation in ~docs/plugins~.
* Code Used
- crappy by Andrew Phillips <theasp@gmail.com> [[http://www.gnu.org/licenses/gpl-2.0.html][GPLv2]] includes code from:
  - ezconfig.lua by Georgi Valkov <georgi.t.valkov@gmail.com> [[http://www.gnu.org/licenses/gpl-2.0.html][GPLv2]]
    - https://raw.githubusercontent.com/gvalkov/dotfiles-awesome/master/ezconfig.lua
  - JSON Encode/Decode in Pure LUA by Jeffrey Friedl  [[http://creativecommons.org/licenses/by/3.0/][CC-BY 3.0]]
    - http://regex.info/blog/lua/json
  - Serpent by Paul Kulchenko [[http://opensource.org/licenses/MIT][MIT]]
   - https://github.com/pkulchenko/serpent
  - rc.lua from Awesome by the awesome project [[http://www.gnu.org/licenses/gpl-2.0.html][GPLv2]]
    - http://awesome.naquadah.org/

# Local variables:
# org-ascii-charset: utf-8
# eval: (add-hook 'after-save-hook '(lambda () (org-ascii-export-to-ascii) (org-html-export-to-html) ) nil t)
# end:
